=== alexisheloir/embr-character-animation-engine/TRUNK/build/win32Build/lightingBoy/EMBRCHConfig.dtd
<!ELEMENT characters (character*)>
<!ELEMENT character (upVector,kinematics+,animations?,shaders?,behaviors?)>
  <!ELEMENT upVector	(#PCDATA)>
  <!ELEMENT kinematics	(jointGroups,kinematicProperties)>
    <!ELEMENT joints	(joint*)>
      <!ELEMENT joint		(DOFS*)>
        <!ELEMENT jointName	(#PCDATA)>
        <!ELEMENT DOFS		(DOF+)>
          <!ELEMENT DOF         EMPTY>
    <!ELEMENT jointGroups (jointGroup*)>
      <!ELEMENT jointGroup (joints)>
        <!ELEMENT jointReference (#PCDATA)>
    <!ELEMENT kinematicProperties (HALStructure*, CCDStructure*, iterativeIKStructure, swivel)>
      <!ELEMENT HALStructure (#PCDATA)>
      <!ELEMENT CCDStructure (#PCDATA)>
      <!ELEMENT iterativeIKStructure (#PCDATA)>
      <!ELEMENT swivel (#PCDATA)>
  <!ELEMENT animations		(#PCDATA)>
  <!ELEMENT shaders (shaderParameters)>
    <!ELEMENT shaderParameters (shaderParameter)>
      <!ELEMENT shaderParameter (#PCDATA)>
  <!ELEMENT behaviors (autonomousParameters*, autonomousBehavior*)>
    <!ELEMENT autonomousParameters (autonomousParameter*)>
      <!ELEMENT autonomousParameter (#PCDATA)>
    <!ELEMENT autonomousBehavior (actuatorMorphAnimation*, actuatorSkelAnimation*)>
      <!ELEMENT actuatorMorphAnimation (morphKey+)>
        <!ELEMENT morphKey (#PCDATA)>
      <!ELEMENT actuatorSkelAnimation (#PCDATA)>

<!ATTLIST character name CDATA #REQUIRED>
<!ATTLIST joint id CDATA #REQUIRED>
<!ATTLIST jointGroup   id  CDATA #REQUIRED
                       sym CDATA #IMPLIED>
<!ATTLIST DOF axis CDATA #REQUIRED
              upperLimit CDATA #REQUIRED
              lowerLimit CDATA #REQUIRED
              gain CDATA #IMPLIED>
<!ATTLIST jointReference   ref  CDATA #REQUIRED>
<!ATTLIST HALStructure ref  CDATA #REQUIRED>
<!ATTLIST CCDStructure ref  CDATA #REQUIRED>
<!ATTLIST iterativeIKStructure ref  CDATA #REQUIRED>
<!ATTLIST swivel ref  CDATA #REQUIRED>
<!ATTLIST autonomousParameter name CDATA #REQUIRED>
<!ATTLIST autonomousParameter initialValue CDATA #REQUIRED>
<!ATTLIST autonomousBehavior name CDATA #REQUIRED>
<!ATTLIST autonomousBehavior frequency CDATA #REQUIRED>
<!ATTLIST autonomousBehavior type CDATA #REQUIRED>
<!ATTLIST actuatorMorphAnimation value CDATA #REQUIRED>
<!ATTLIST morphKey name CDATA #REQUIRED>
<!ATTLIST morphKey relativeKey CDATA #REQUIRED>
<!ATTLIST morphKey value CDATA #REQUIRED>
<!ATTLIST actuatorSkelAnimation animation CDATA #REQUIRED>
<!ATTLIST actuatorSkelAnimation jointGroup CDATA #REQUIRED>
<!ATTLIST actuatorSkelAnimation useVelocity CDATA #REQUIRED>
<!ATTLIST actuatorSkelAnimation value CDATA #REQUIRED>
<!ATTLIST randomBehavior name CDATA #REQUIRED>
<!ATTLIST randomBehavior probability CDATA #REQUIRED>
<!ATTLIST shaderParameter name CDATA #REQUIRED>
<!ATTLIST shaderParameter initialValue CDATA #REQUIRED>

=== alexisheloir/embr-character-animation-engine/TRUNK/build/linuxBuild/game/characterConfiguration.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE characters SYSTEM "./EMBRCHConfig.dtd">
<characters>
  <character name="Amber">
    <upVector>Z</upVector>
    <kinematics>
    <jointGroups>
      <jointGroup id="leye" sym="left">
	<joints>
	  <joint id="leye">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="10" lowerLimit="-10" gain="0.01"/>
	      <DOF axis="Zaxis" upperLimit="20" lowerLimit="-20" gain="0.01"/>
	    </DOFS>
	  </joint>
	  <joint id="leyeEnd">
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="reye" sym="right">
	<joints>
	  <joint id="reye">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="10" lowerLimit="-10" gain="0.01"/>
	      <DOF axis="Zaxis" upperLimit="20" lowerLimit="-20" gain="0.01"/>
	    </DOFS>
	  </joint>
	  <joint id="reyeEnd">
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="head">
	<joints>
	  <joint id="head">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="30" lowerLimit="-40" gain="0.02"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.04"/>
	      <DOF axis="Zaxis" upperLimit="8" lowerLimit="-8" gain="0.02"/>
	    </DOFS>
	  </joint>
	  <joint id="headDir">
	  </joint>
	  <joint id="headEnd">
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="headNeck">
	<joints>
	  <joint id="neck">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="8" lowerLimit="-8" gain="0.0002"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.004"/>
	      <DOF axis="Zaxis" upperLimit="30" lowerLimit="-30" gain="0.004"/>
	    </DOFS>
	  </joint>
	  <joint id="head">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="30" lowerLimit="-40" gain="0.02"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.04"/>
	      <DOF axis="Zaxis" upperLimit="40" lowerLimit="-40" gain="0.04"/>
	    </DOFS>
	  </joint>
	  <joint id="headDir">
	  </joint>
	  <joint id="headEnd">
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="headThorax">
	<joints>
	  <joint id="spine3">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="8" lowerLimit="-8" gain="0.002"/>
	    </DOFS>
	  </joint>
	  <joint id="spine4">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="8" lowerLimit="-8" gain="0.003"/>
	    </DOFS>
	  </joint>
	  <joint id="neck">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="15" lowerLimit="-15" gain="0.002"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.004"/>
	    </DOFS>
	  </joint>
	  <joint id="head">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="30" lowerLimit="-40" gain="0.02"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.04"/>
	      <DOF axis="Zaxis" upperLimit="8" lowerLimit="-8" gain="0.02"/>
	    </DOFS>
	  </joint>
	  <joint id="headDir">
	  </joint>
	  <joint id="headEnd">
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="headAbdomen">
	<joints>
	  <joint id="spine1">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="4" lowerLimit="-4" gain="0.001"/>
	      <DOF axis="Zaxis" upperLimit="4" lowerLimit="-4" gain="0.001"/>
	    </DOFS>
	  </joint>
	  <joint id="spine2">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="6" lowerLimit="-6" gain="0.002"/>
	    </DOFS>
	  </joint>	  
	  <joint id="spine3">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="8" lowerLimit="-8" gain="0.002"/>
	    </DOFS>
	  </joint>
	  <joint id="spine4">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="8" lowerLimit="-8" gain="0.003"/>
	    </DOFS>
	  </joint>
	  <joint id="neck">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="15" lowerLimit="-15" gain="0.002"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.004"/>
	    </DOFS>
	  </joint>
	  <joint id="head">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="30" lowerLimit="-40" gain="0.02"/>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.04"/>
	      <DOF axis="Zaxis" upperLimit="8" lowerLimit="-8" gain="0.02"/>
	    </DOFS>
	  </joint>
	  <joint id="headDir">
	  </joint>
	  <joint id="headEnd">
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="upperBodyNoArms">
	<joints>
	  <joint id="spine1"/>
	  <joint id="spine2"/>
	  <joint id="spine3"/>
	  <joint id="spine4"/>
	</joints>
      </jointGroup>
      <jointGroup id="lhand">
	<joints>
	  <joint id="l1Mcp"/>
	  <joint id="l1Prox"/>
	  <joint id="l1Dist"/>
	  <joint id="l2Mcp"/>
	  <joint id="l2Prox"/>
	  <joint id="l2Dist"/>
	  <joint id="l3Mcp"/>
	  <joint id="l3Prox"/>
	  <joint id="l3Dist"/>
	  <joint id="l4Mcp"/>
	  <joint id="l4Prox"/>
	  <joint id="l4Dist"/>
	  <joint id="l5Mcp"/>
	  <joint id="l5Prox"/>
	  <joint id="l5Dist"/>
	</joints>
      </jointGroup>
      <jointGroup id="rhand">
	<joints>
	  <joint id="r1Mcp"/>
	  <joint id="r1Prox"/>
	  <joint id="r1Dist"/>
	  <joint id="r2Mcp"/>
	  <joint id="r2Prox"/>
	  <joint id="r2Dist"/>
	  <joint id="r3Mcp"/>
	  <joint id="r3Prox"/>
	  <joint id="r3Dist"/>
	  <joint id="r4Mcp"/>
	  <joint id="r4Prox"/>
	  <joint id="r4Dist"/>
	  <joint id="r5Mcp"/>
	  <joint id="r5Prox"/>
	  <joint id="r5Dist"/>
	</joints>
      </jointGroup>
      <jointGroup id="rarm" sym="right">
	<joints>
	  <joint id="rclavicle">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="10" lowerLimit="-10" gain="0.05"/>
	      <DOF axis="Yaxis" upperLimit="8" lowerLimit="-8" gain="0.00"/>
	      <DOF axis="Zaxis" upperLimit="20" lowerLimit="-20" gain="0.05"/>
	    </DOFS>
	  </joint>
	  <joint id="rhumerus">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="75" lowerLimit="-60" gain="0.05"/>
	      <DOF axis="Yaxis" upperLimit="120" lowerLimit="-120" gain="0.05"/>
	      <DOF axis="Zaxis" upperLimit="100" lowerLimit="15" gain="0.05"/>
	    </DOFS>
	  </joint>
	  <joint id="rradius">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.1"/>
	      <DOF axis="Zaxis" upperLimit="150" lowerLimit="0" gain="0.08"/>
	    </DOFS>
	  </joint>
	  <joint id="rhand">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="90" lowerLimit="-90" gain="1.0"/>
	      <DOF axis="Yaxis" upperLimit="90" lowerLimit="-90" gain="1.0"/>
	      <DOF axis="Zaxis" upperLimit="60" lowerLimit="-60" gain="1.0"/>
	    </DOFS>
	  </joint>
	</joints>
      </jointGroup>
      <jointGroup id="larm" sym="left">
	<joints>
	  <joint id="lclavicle">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="10" lowerLimit="-10" gain="0.05"/>
	      <DOF axis="Yaxis" upperLimit="8" lowerLimit="-8" gain="0.00"/>
	      <DOF axis="Zaxis" upperLimit="20" lowerLimit="-20" gain="0.05"/>
	    </DOFS>
	  </joint>
	  <joint id="lhumerus">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="75" lowerLimit="-60" gain="0.05"/>
	      <DOF axis="Yaxis" upperLimit="120" lowerLimit="-120" gain="0.05"/>
	      <DOF axis="Zaxis" upperLimit="-15" lowerLimit="-100" gain="0.05"/>
	    </DOFS>
	  </joint>
	  <joint id="lradius">
	    <DOFS>
	      <DOF axis="Yaxis" upperLimit="30" lowerLimit="-30" gain="0.1"/>
	      <DOF axis="Zaxis" upperLimit="0" lowerLimit="-150" gain="0.08"/>
	    </DOFS>
	  </joint>
	  <joint id="lhand">
	    <DOFS>
	      <DOF axis="Xaxis" upperLimit="90" lowerLimit="-90" gain="1.0"/>
	      <DOF axis="Yaxis" upperLimit="90" lowerLimit="-90" gain="1.0"/>
	      <DOF axis="Zaxis" upperLimit="60" lowerLimit="-60" gain="1.0"/>
	    </DOFS>
	  </joint>
	</joints>
      </jointGroup>
    </jointGroups>
    <kinematicProperties>
      <HALStructure ref="larm">
      </HALStructure>
      <CCDStructure ref="larm">
      </CCDStructure>
      <iterativeIKStructure ref="larm">
      </iterativeIKStructure>
      <swivel ref="larm">
      </swivel>
    </kinematicProperties>
  </kinematics>

    <animations>

    </animations>

    <shaders>
      <shaderParameters>
        <shaderParameter name="blushing" initialValue="0.0"/>
      </shaderParameters>
    </shaders>
 
    <behaviors>
      <autonomousParameters>
        <autonomousParameter name="breathingFrequency" initialValue="0.35"/>
        <autonomousParameter name="breathingAmplitude" initialValue="0.1"/>
        <autonomousParameter name="blinkIntensity" initialValue="1.0"/>
        <autonomousParameter name="blinkProbability" initialValue="4000.0"/>
      </autonomousParameters>
      <autonomousBehavior name="breathing" type="periodic" frequency="breathingFrequency">
        <actuatorMorphAnimation value="breathingAmplitude">
          <morphKey name="inspire" relativeKey="0.0"  value="0.5"/>
          <morphKey name="inspire" relativeKey="0.25" value="1.0 "/>
          <morphKey name="inspire" relativeKey="0.75" value="0.0 "/>
          <morphKey name="inspire" relativeKey="1.0"  value="0.5"/>
        </actuatorMorphAnimation>
        <actuatorSkelAnimation animation="breathing" jointGroup="all" useVelocity="True" value="breathingAmplitude"/>
      </autonomousBehavior>
      <autonomousBehavior name="blinking" type="random" frequency="blinkProbability">
        <actuatorMorphAnimation value="blinkIntensity">
          <morphKey name="ModBlinkLeft" relativeKey="0.0"  value="0.0"/>
          <morphKey name="ModBlinkLeft" relativeKey="0.5" value="1.0 "/>
          <morphKey name="ModBlinkLeft" relativeKey="1.0" value="0.0 "/>
          <morphKey name="ModBlinkRight" relativeKey="0.0"  value="0.0"/>
          <morphKey name="ModBlinkRight" relativeKey="0.5" value="1.0 "/>
          <morphKey name="ModBlinkRight" relativeKey="1.0" value="0.0 "/>
        </actuatorMorphAnimation>
      </autonomousBehavior>
    </behaviors>
  </character>
</characters>
